CREATE TABLE Organizer
(
	OrgID INT IDENTITY(1,1) PRIMARY KEY,
	OrgName VARCHAR(50),
)

CREATE TABLE Competition
(
	CompID INT IDENTITY(1,1) PRIMARY KEY,
	CompName VARCHAR(100) UNIQUE,
	CompStatus VARCHAR(15),
	OrgID INT NOT NULL UNIQUE FOREIGN KEY REFERENCES Organizer(OrgID),
)

CREATE TABLE Prize
(
	PrizeID INT IDENTITY(1,1) PRIMARY KEY,
	ParticipationPrize INT,
	WinnerPrize INT,
)

CREATE TABLE Edition
(
	EditionID INT IDENTITY(1,1) PRIMARY KEY,
	CompID INT NOT NULL FOREIGN KEY REFERENCES Competition(CompID),
	EditionYear INT NOT NULL,
	Champions VARCHAR(50),
	PrizeID INT NOT NULL FOREIGN KEY REFERENCES Prize(PrizeID),
)


CREATE TABLE Sport
(
	SportID INT IDENTITY(1,1) PRIMARY KEY,
	SportName VARCHAR(50) UNIQUE,
	SportType VARCHAR(50),
	NrOfPlayers SMALLINT
)

CREATE TABLE Sponsor
(
	SponsorID INT IDENTITY(1,1) PRIMARY KEY,
	SponsorName VARCHAR(50),
	Domain VARCHAR(50),
)

CREATE TABLE Country
(
	CountryID INT IDENTITY(1,1) PRIMARY KEY,
	CountryName VARCHAR(50),
	Capital VARCHAR(50),
)

CREATE TABLE Coach
(
	CoachID INT IDENTITY(1,1) PRIMARY KEY,
	CoachName VARCHAR(30),
	Salary INT,
	CountryID INT NOT NULL FOREIGN KEY REFERENCES Country(CountryID),
)

CREATE TABLE Participant
(
	PID INT IDENTITY(1,1) PRIMARY KEY,
	PName VARCHAR(50),
	PType VARCHAR(20),
	SportID INT NOT NULL FOREIGN KEY REFERENCES Sport(SportID),
	SponsorID INT NOT NULL FOREIGN KEY REFERENCES Sponsor(SponsorID),
	CoachID INT NOT NULL UNIQUE FOREIGN KEY REFERENCES Coach(CoachID),
	CountryID INT NOT NULL FOREIGN KEY REFERENCES Country(CountryID),
)

CREATE TABLE Participates_in
(
	EditionID INT NOT NULL FOREIGN KEY REFERENCES Edition(EditionID),
	Round_reached VARCHAR(50),
	Best_performance VARCHAR(50),
	PID INT NOT NULL FOREIGN KEY REFERENCES Participant(PID),
	PRIMARY KEY (EditionID, PID),
)

CREATE TABLE Belongs_in
(
	CompID INT NOT NULL FOREIGN KEY REFERENCES Competition(CompID),
	SportID INT,
	TournamentType VARCHAR(50),
	PRIMARY KEY (CompID, SportID),
	FOREIGN KEY (SportID) REFERENCES Sport (SportID),
	IsMainSport CHAR(3),
)


CREATE TABLE Location
(
	CityName VARCHAR(50),
	LID INT IDENTITY(1,1) PRIMARY KEY,
	NrOfVenues INT NOT NULL,
	CountryID INT NOT NULL FOREIGN KEY REFERENCES Country(CountryID),
)

CREATE TABLE Takes_place
(
	EditionID INT NOT NULL FOREIGN KEY REFERENCES Edition(EditionID),
	LID INT NOT NULL FOREIGN KEY REFERENCES Location(LID),
	PRIMARY KEY (EditionID, LID),
	Date DATE,
)